### ISSUE TITLE
renderComponents is not defined

### ISSUE THREAD

**Issue by ChennyBaBy** [opencomponents/oc-client-node#94]
I'm getting a `renderComponents is not defined` error when i try to call the `client.init` function, using version `"^3.2.4"` of the module and node.js version `6.10.0`.

Here's the code where i was calling the init function: https://gist.github.com/ChennyBaBy/b04ffe0e3f069d0d5608718ba12ea39a

I think i'm missing something obvious but i couldn't figure out what im missing from the readme.

```js
path/to/node_modules/oc-client/src/index.js:34
      const renderComponents = options.renderComponents || renderComponents;
                                                           ^
ReferenceError: renderComponents is not defined
```

**Comment by wsalazar-peakactivity** [comment]
I'm getting the same thing. Were you able to work around this? Any insights would be helpful.

**Comment by wsalazar-peakactivity** [comment]
I have an open pr that fixes the issue on my side:
https://github.com/opencomponents/oc-client-node/pull/95

**Comment by matteofigus** [comment]
Merged and released. Thanks!
